dataset: caltech101
backbone: robust_vit_base_patch16_224
ft_type: full_fine_tuning
loss_function: TRADES_v2
seed: 1
epochs: 5
lr1: 0.010516039540919314
lr2: 0.010363459483491242
weight_decay1: 0.004921507397015504
weight_decay2: 0.0007016152732955533
use_rs: false
epsilon: 0.015686275
step_size: 0.007843137
perturb_steps: 10
distance: Linf
beta: 1.0
project_name: full_fine_tuning_5epochs_final1
